name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: The-Nest-Trail-Frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: The-Nest-Trail-Frontend/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        # Provide API URL at build time (set this secret in repo Settings > Secrets and variables > Actions)
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

      # Optional but recommended: SPA fallback so refresh/deep links work
      - name: Copy 404 for SPA
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: The-Nest-Trail-Frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4